### PR TITLE
fix noise on single qubit measurements in em3 model

### PR DESCRIPTION
**Pull request by newmanmg**

### CODE REVIEW

**Comment by Strilanc** [comment]
I'm hesitant to merge this as it will desync the code from the paper.

**Review by Strilanc — CHANGES_REQUESTED** [review]
Because we are changing the noise model we need to increment the version number from "EM3_v2" to "EM3_v3". Otherwise it's too easy to confuse recorded data. Once that's done it can be merged.

**Review by Strilanc — CHANGES_REQUESTED** [review]
You have this as an EM3_v3 now right? Merge with main to get matt's changes then push and let me know to review.

**Review by Strilanc — CHANGES_REQUESTED** [review]
This change isn't doing what it's supposed to.

It's *supposed to* define EM3v3 with these changed semantics while leaving EM3v2 exactly the same as in the first release. You've instead redefined EM3v2.

I'm surprised no tests failed, actually. I must have forgotten to include tests that EM3v2 did a specific thing..

**Comment by newmanmg** [comment]
> This change isn't doing what it's supposed to.
> 
> It's _supposed to_ define EM3v3 with these changed semantics while leaving EM3v2 exactly the same as in the first release. You've instead redefined EM3v2.
> 
> I'm surprised no tests failed, actually. I must have forgotten to include tests that EM3v2 did a specific thing..

Just pushed a test that rightly fails.  Adding v3 just currently having a small war with my cloudtop.

**Review by Strilanc — APPROVED** [review]

**Pull request merged**
